const defaultTheme = require("tailwindcss/defaultTheme")

module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    // "./modules/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      amber: {
        1: "#FFF3EB",
      },
      black: "#000",
      white: "#fff",
      "mint-bg": "#50CEA8",
      "mint-dark": "#85E4C7",
      mint: "#A5ECD5",
      "mint-light": "#D1F9EC",
      // "mint2-light": "#DCFFF4",
      "punch-dark": "#FEB169",
      punch: "#FFC28D",
      "punch-light": "#FFE0C3",
      "green-secondary-dark": "#00B26E",
      "green-secondary-light": "#BFEAD0",
      // "green-darker": "#27AE60",
      "green-dark": "#5EC569",
      green: "#81D05F",
      "green-light": "#A1DD85",
      green2: "#4EC7A2",
      "yellow-dark": "#FFD74D",
      yellow: "#FFE37B",
      "yellow-light": "#FFEA9E",
      "red-dark": "#EA4745",
      "red-sign": "#EA4846",
      red: "#ef7171",
      "red-light": "#F69291",
      "blue-dark": "#1A88AF",
      blue: "#64A2C1",
      "blue-light": "#8FB8D0",
      "orange-dark": "#E88A36",
      orange: "#F3A268",
      "orange-light": "#F6B78D",
      "brown-dark": "#955542",
      brown: "#B98B7E",
      "brown-light": "#D8B5AB",
      "pink-light": "#FFD9D9",
      "pastel-green-light": "#B4EBCF",
      "pastel-green-dark": "#5BC68F",
      "pastel-blue-light": "#D5F2FF",
      "pastel-blue-dark": "#7BD3FC",
      "pastel-red-light": "#FFC7CC",
      "pastel-red-dark": "#F94151",
      purple: "#D5A6FB",
      gray: {
        1: "#DADADA",
        2: "#4F4F4F",
        3: "#828282",
        4: "#E2E2E2",
        100: "#e6e6e6",
        200: "#cccccc",
        300: "#b3b3b3",
        400: "#999999",
        500: "#808080",
        600: "#666666",
        700: "#4d4d4d",
        800: "#333333",
        900: "#1a1a1a",
      },
      "gray-border": "#E0E0E0",
      "gray-placeholder": "#BDBDBD",
      "white-hover": "#DEDEDE",
      "btn-hover": "#13607B",
      checkbox: "#1783DC",
      "btn-disable": "#E7E7E7",
      bullet: "#A5ECD5",
      "blue-mybalance": "#F2F7FF",
      "btn-yellow": "#FFCA12",
      "nft-normal": "#5BC68F",
      "nft-rare": "#41C6F1",
      "nft-super-rare": "#F9C956",
      "nft-special-super-rare": "#EA4945",
    },
    extend: {
      flexGrow: {
        2: "2",
      },
      screens: {
        "2sm": "375px",
        md: "430px",
        lg: "1025px",
        "2lg": "1280px",
        xl: "1920px",
      },
      height: {
        28.5: "118px",
        800: "800px",
        950: "950px",
      },
      boxShadow: {
        custom: "0px 3.19537px 3.19537px rgba(0, 0, 0, 0.25)",
        menu: "0px 0px 10px 2px rgba(0, 0, 0, 0.1)",
      },
      fontFamily: {
        sans: ["Inter", ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        "2xs": "10px",
      },
      animation: {
        hand: "wiggle 1s infinite",
        bounceItem: "bounce1 0.3s infinite",
        fadeIn: "fadeIn 1s ease-in forwards",
        movingBg: "movingBg 100s linear infinite",
        animatedBg: "animatedBackground 15s linear infinite alternate",
        movingBgSection1Lg: "movingBgSection1Lg 20s linear infinite",
      },
      keyframes: {
        wiggle: {
          "0%, 100%": { transform: "rotate(0deg)" },
          "50%": { transform: "rotate(20deg)" },
        },
        bounce1: {
          "0%": { transform: "translateY(-1px)" },
          "50%": { transform: "translateY(0px)" },
          "100%": { transform: "translateY(-1px)" },
        },
        fadeIn: {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        movingBg: {
          "0%": { transform: "translateX(0%)" },
          "50%": { transform: "translateX(calc(-100% + 100vw))" },
          "100%": { transform: "translateX(0%)" },
        },
        movingBgSection1Lg: {
          "0%": { transform: "translateX(0%)" },
          "50%": { transform: "translateX(calc(-100% + 62.5vw))" },
          "100%": { transform: "translateX(0%)" },
        },
        animatedBackground: {
          "0%": { backgroundPosition: "0 0" },
          "100%": { backgroundPosition: "100% 0" },
        },
      },
    },
  },
  plugins: [
    require("@headlessui/tailwindcss"),
    require("tw-elements/dist/plugin"),
  ],
}
